<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MultiMon.Core\MultiMon.Core.csproj" />
    <ProjectReference Include="..\MultiMon.Graphics\MultiMon.Graphics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.MediaFoundation" Version="3.8.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
